//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apartman.Models.veritabanı
{
    using System;
    using System.Collections.Generic;
    
    public partial class arac_bilgileri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public arac_bilgileri()
        {
            this.park_yeri = new HashSet<park_yeri>();
        }
    
        public int arac_id { get; set; }
        public string arac_plaka { get; set; }
        public string arac_marka { get; set; }
        public string arac_renk { get; set; }
        public int kisi_id { get; set; }
    
        public virtual kisi_bilgileri kisi_bilgileri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<park_yeri> park_yeri { get; set; }
    }
}
