//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apartman.Models.veritabanı
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class apartmanEntities : DbContext
    {
        public apartmanEntities()
            : base("name=apartmanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<arac_bilgileri> arac_bilgileri { get; set; }
        public virtual DbSet<kisi_bilgileri> kisi_bilgileri { get; set; }
        public virtual DbSet<park_yeri> park_yeri { get; set; }
    }
}
