//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apartman.Models.veritabanı
{
    using System;
    using System.Collections.Generic;
    
    public partial class park_yeri
    {
        public int parkyeri_id { get; set; }
        public string Parkyeri { get; set; }
        public int arac_id { get; set; }
    
        public virtual arac_bilgileri arac_bilgileri { get; set; }
    }
}
